version: "3"
services:
  db:
    image: obserfy/postgres-dev:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    volumes:
      - leonidas:/var/lib/postgresql/data

volumes:
  leonidas:
